### ISSUE TITLE
ffmpeg, Downloads as a queued tasks 

### ISSUE THREAD

**Issue by heret0x0** [heret0x0/Mushroom#4]
it will be nice if active downloads number are **configurable** in preferences _but no more than 5 for example_
while active ffmpeg tasks should be **ONLY** 1

those might be done by a list or something and a function that if it once called it iterates over the list to finish its tasks and if there is active tasks it just adds them to the list

- [x] FFMPEG (ez)
- [ ] Downloads (Hard)

**Comment by azab246** [comment]
smh i think that doing that with downloads will make it a pure mess + tons of work so ill cancel that at least for now

**Comment by heret0x0** [comment]
smh i think that doing that with downloads will make it a pure mess + tons of work so ill cancel that at least for now

so i think we r ready to go now :D
